steps:

# DOCKER BUILD & PUSH WEB
- id: docker-build-http
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/wedding-http:$REVISION_ID'
  - '-f'
  - './nginx/Dockerfile'
  - '.'
  waitFor:
  - '-'
- id: docker-push-http
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/wedding-http:$REVISION_ID'
  waitFor:
  - docker-build-http

# DOCKER BUILD & PUSH MIGRATE
- id: docker-build-migrate
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/wedding-migrate:$REVISION_ID'
  - '-f'
  - './migrate/Dockerfile'
  - '.'
  waitFor:
  - '-'
- id: docker-push-migrate
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/wedding-migrate:$REVISION_ID'
  waitFor:
  - docker-build-migrate

# DOCKER BUILD & PUSH APP
- id: docker-build-app
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/wedding-app:$REVISION_ID'
  - '-f'
  - './app/Dockerfile'
  - '.'
  waitFor:
  - '-'
- id: docker-push-app
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/wedding-app:$REVISION_ID'
  waitFor:
  - docker-build-app

# KUBE SUPPORTS
- id: kube-infrastructure
  name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'apply'
  - '--filename=kube/infrastructure/'
  - '--location=us-central1-a'
  - '--cluster=deepthought'
  waitFor:
  - docker-push-http
  - docker-push-migrate
  - docker-push-app

# MIGRATION
- id: migrate
  name: 'gcr.io/$PROJECT_ID/run-kube-job:latest'
  env:
  - PROJECT=$PROJECT_ID
  - ZONE=us-central1-a
  - CLUSTER=deepthought
  - NAME=wedding-migrate
  - SPEC=./kube/app/migrate.job.yaml
  - TAG=$REVISION_ID
  waitFor:
  - docker-push-migrate
  - docker-push-http
  - docker-push-app

# KUBE DEPLOYMENTS
- id: kube-http-deployment
  name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--filename=kube/app/http.deployment.yaml'
  - '--image=gcr.io/$PROJECT_ID/wedding-http:$REVISION_ID'
  - '--location=us-central1-a'
  - '--cluster=deepthought'
  - '--output=./output/http'
  waitFor:
  - migrate
- id: kube-app-deployment
  name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--filename=kube/app/app.deployment.yaml'
  - '--image=gcr.io/$PROJECT_ID/wedding-app:$REVISION_ID'
  - '--location=us-central1-a'
  - '--cluster=deepthought'
  - '--output=./output/app'
  waitFor:
  - migrate

images:
- 'gcr.io/$PROJECT_ID/wedding-http:$REVISION_ID'
- 'gcr.io/$PROJECT_ID/wedding-migrate:$REVISION_ID'
- 'gcr.io/$PROJECT_ID/wedding-app:$REVISION_ID'
