steps:

# DOCKER BUILD & PUSH WEB
- id: docker-build-web
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/wedding-http:$REVISION_ID'
  - '-f'
  - './nginx/Dockerfile'
  - '.'
  waitFor:
  - '-'
- id: docker-push-web
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/wedding-http:$REVISION_ID'
  waitFor:
  - docker-build-web

# DOCKER BUILD & PUSH MIGRATE
- id: docker-build-migrate
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/wedding-migrate:$REVISION_ID'
  - '-f'
  - './migrate/Dockerfile'
  - '.'
  waitFor:
  - '-'
- id: docker-push-migrate
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/wedding-migrate:$REVISION_ID'
  waitFor:
  - docker-build-migrate

# DOCKER BUILD & PUSH APP
- id: docker-build-app
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/wedding-app:$REVISION_ID'
  - '-f'
  - './app/Dockerfile'
  - '.'
  waitFor:
  - '-'
- id: docker-push-app
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/wedding-app:$REVISION_ID'
  waitFor:
  - docker-build-app

# KUBE SUPPORTS
- id: kube-http-ingress
  name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'apply'
  - '--filename=kube/http.ingress.yaml'
  - '--location=us-central1-a'
  - '--cluster=deepthought'
  waitFor:
  - docker-push-web
  - docker-push-migrate
  - docker-push-app
- id: kube-http-service
  name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'apply'
  - '--filename=kube/http.service.yaml'
  - '--location=us-central1-a'
  - '--cluster=deepthought'
  waitFor:
  - docker-push-web
  - docker-push-migrate
  - docker-push-app
- id: kube-app-service
  name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'apply'
  - '--filename=kube/app.service.yaml'
  - '--location=us-central1-a'
  - '--cluster=deepthought'
  waitFor:
  - docker-push-web
  - docker-push-migrate
  - docker-push-app

# MIGRATION
- id: migrate
  name: 'gcr.io/$PROJECT_ID/run-kube-job:latest'
  env:
  - PROJECT=$PROJECT_ID
  - ZONE=us-central1-a
  - CLUSTER=deepthought
  - NAME=wedding-migrate
  - SPEC=./kube/migrate.job.yaml
  - TAG=$REVISION_ID
  waitFor:
  - docker-push-migrate
  - docker-push-web
  - docker-push-app

# # KUBE DEPLOYMENTS
- id: kube-http-deployment
  name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--filename=kube/http.deployment.yaml'
  - '--image=gcr.io/$PROJECT_ID/wedding-http:$REVISION_ID'
  - '--location=us-central1-a'
  - '--cluster=deepthought'
  waitFor:
  - migrate
- id: kube-app-deployment
  name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--filename=kube/app.deployment.yaml'
  - '--image=gcr.io/$PROJECT_ID/wedding-app:$REVISION_ID'
  - '--location=us-central1-a'
  - '--cluster=deepthought'
  waitFor:
  - migrate

images:
- 'gcr.io/$PROJECT_ID/wedding-http:$REVISION_ID'
- 'gcr.io/$PROJECT_ID/wedding-migrate:$REVISION_ID'
- 'gcr.io/$PROJECT_ID/wedding-app:$REVISION_ID'
