steps:

- id: build-http
  name: 'gcr.io/$PROJECT_ID/docker-build-push-tag:latest'
  env:
  - PROJECT_ID=$PROJECT_ID
  - REVISION_ID=$REVISION_ID
  - IMAGE_NAME=wedding-http
  - ROOT_PATH=.
  - DOCKERFILE=./nginx/Dockerfile
  waitFor:
  - '-'
- id: build-migrate
  name: 'gcr.io/$PROJECT_ID/docker-build-push-tag:latest'
  env:
  - PROJECT_ID=$PROJECT_ID
  - REVISION_ID=$REVISION_ID
  - IMAGE_NAME=wedding-migrate
  - ROOT_PATH=.
  - DOCKERFILE=./migrate/Dockerfile
  waitFor:
  - '-'
- id: build-app
  name: 'gcr.io/$PROJECT_ID/docker-build-push-tag:latest'
  env:
  - PROJECT_ID=$PROJECT_ID
  - REVISION_ID=$REVISION_ID
  - IMAGE_NAME=wedding-app
  - ROOT_PATH=.
  - DOCKERFILE=./app/Dockerfile
  waitFor:
  - '-'

# KUBE SUPPORTS
- id: kube-infrastructure
  name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'apply'
  - '--filename=kube/infrastructure/'
  - '--location=us-central1-a'
  - '--cluster=deepthought-nu'
  waitFor:
  - build-http
  - build-migrate
  - build-app

# MIGRATION
- id: migrate
  name: 'gcr.io/$PROJECT_ID/run-kube-job:latest'
  env:
  - PROJECT=$PROJECT_ID
  - ZONE=us-central1-a
  - CLUSTER=deepthought-nu
  - NAME=wedding-migrate
  - SPEC=./kube/app/migrate.job.yaml
  - TAG=$REVISION_ID
  waitFor:
  - build-migrate
  - build-http
  - build-app

# KUBE DEPLOYMENTS
- id: kube-http-deployment
  name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--filename=kube/app/http.deployment.yaml'
  - '--image=gcr.io/$PROJECT_ID/wedding-http:$REVISION_ID'
  - '--location=us-central1-a'
  - '--cluster=deepthought-nu'
  - '--output=./output/http'
  waitFor:
  - migrate
- id: kube-app-deployment
  name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--filename=kube/app/app.deployment.yaml'
  - '--image=gcr.io/$PROJECT_ID/wedding-app:$REVISION_ID'
  - '--location=us-central1-a'
  - '--cluster=deepthought-nu'
  - '--output=./output/app'
  waitFor:
  - migrate

images:
- 'gcr.io/$PROJECT_ID/wedding-http:$REVISION_ID'
- 'gcr.io/$PROJECT_ID/wedding-migrate:$REVISION_ID'
- 'gcr.io/$PROJECT_ID/wedding-app:$REVISION_ID'
