version: "3.7"
services:
  mocking-server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - target: 80
      published: 8281
      protocol: tcp
      mode: host
    volumes:
    - type: bind
      source: ./site
      target: /app/site
    - type: bind
      source: ./nginx
      target: /etc/nginx
