apiVersion: v1
kind: Service
metadata:
  name: wedding-app
  labels:
    app: wedding-app
spec:
  type: ExternalName
  externalName: weddingapp.cluster
  selector:
    app: wedding-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
