apiVersion: batch/v1
kind: Job
metadata:
  name: {JOBNAME}
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: wedding-migrate
        image: gcr.io/deepthought-collective/wedding-migrate:{TAG}
        volumeMounts:
        - name: config
          mountPath: "/secret"
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: config
        secret:
          secretName: wedding
